In [1]:
import numpy as np
import pandas as pd

In [2]:
link = "Data/Automobile_data.csv"

In [3]:
dataset = pd.read_csv(link)

In [49]:
dataset.head(20)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.4,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.4,8.0,115,5500,18,22,17450
5,2,?,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.4,8.5,110,5500,19,25,15250
6,1,158,audi,gas,std,four,sedan,fwd,front,105.8,...,136,mpfi,3.19,3.4,8.5,110,5500,19,25,17710
7,1,?,audi,gas,std,four,wagon,fwd,front,105.8,...,136,mpfi,3.19,3.4,8.5,110,5500,19,25,18920
8,1,158,audi,gas,turbo,four,sedan,fwd,front,105.8,...,131,mpfi,3.13,3.4,8.3,140,5500,17,20,23875
9,0,?,audi,gas,turbo,two,hatchback,4wd,front,99.5,...,131,mpfi,3.13,3.4,7.0,160,5500,16,22,?
10,2,192,bmw,gas,std,two,sedan,rwd,front,101.2,...,108,mpfi,3.5,2.8,8.8,101,5800,23,29,16430
11,0,192,bmw,gas,std,four,sedan,rwd,front,101.2,...,108,mpfi,3.5,2.8,8.8,101,5800,23,29,16925
12,0,188,bmw,gas,std,two,sedan,rwd,front,101.2,...,164,mpfi,3.31,3.19,9.0,121,4250,21,28,20970
13,0,188,bmw,gas,std,four,sedan,rwd,front,101.2,...,164,mpfi,3.31,3.19,9.0,121,4250,21,28,21105
14,1,?,bmw,gas,std,four,sedan,rwd,front,103.5,...,164,mpfi,3.31,3.19,9.0,121,4250,20,25,24565
15,0,?,bmw,gas,std,four,sedan,rwd,front,103.5,...,209,mpfi,3.62,3.39,8.0,182,5400,16,22,30760
16,0,?,bmw,gas,std,two,sedan,rwd,front,103.5,...,209,mpfi,3.62,3.39,8.0,182,5400,16,22,41315
17,0,?,bmw,gas,std,four,sedan,rwd,front,110.0,...,209,mpfi,3.62,3.39,8.0,182,5400,15,20,36880
18,2,121,chevrolet,gas,std,two,hatchback,fwd,front,88.4,...,61,2bbl,2.91,3.03,9.5,48,5100,47,53,5151
19,1,98,chevrolet,gas,std,two,hatchback,fwd,front,94.5,...,90,2bbl,3.03,3.11,9.6,70,5400,38,43,6295

In [6]:
dataset.dtypes

symboling              int64
normalized-losses     object
make                  object
fuel-type             object
aspiration            object
num-of-doors          object
body-style            object
drive-wheels          object
engine-location       object
wheel-base           float64
length               float64
width                float64
height               float64
curb-weight            int64
engine-type           object
num-of-cylinders      object
engine-size            int64
fuel-system           object
bore                  object
stroke                object
compression-ratio    float64
horsepower            object
peak-rpm              object
city-mpg               int64
highway-mpg            int64
price                 object
dtype: object

In [8]:
lista_carros = list(dataset["make"])

In [11]:
dataset["make"].unique()

array(['alfa-romero', 'audi', 'bmw', 'chevrolet', 'dodge', 'honda',
       'isuzu', 'jaguar', 'mazda', 'mercedes-benz', 'mercury',
       'mitsubishi', 'nissan', 'peugot', 'plymouth', 'porsche', 'renault',
       'saab', 'subaru', 'toyota', 'volkswagen', 'volvo'], dtype=object)

In [9]:
type(lista_carros)

list

In [40]:
def comparacion_conteo(n_value):
    contador = 0
    if(n_value=="audi"):
        contador =1
    print(contador)
    #return contador

In [35]:
comparacion_conteo(lista_carros)

0

In [36]:
cconteo = map(comparacion_conteo,lista_carros)

In [32]:
lista_carros

(['alfa-romero',
  'alfa-romero',
  'alfa-romero',
  'audi',
  'audi',
  'audi',
  'audi',
  'audi',
  'audi',
  'audi',
  'bmw',
  'bmw',
  'bmw',
  'bmw',
  'bmw',
  'bmw',
  'bmw',
  'bmw',
  'chevrolet',
  'chevrolet',
  'chevrolet',
  'dodge',
  'dodge',
  'dodge',
  'dodge',
  'dodge',
  'dodge',
  'dodge',
  'dodge',
  'dodge',
  'honda',
  'honda',
  'honda',
  'honda',
  'honda',
  'honda',
  'honda',
  'honda',
  'honda',
  'honda',
  'honda',
  'honda',
  'honda',
  'isuzu',
  'isuzu',
  'isuzu',
  'isuzu',
  'jaguar',
  'jaguar',
  'jaguar',
  'mazda',
  'mazda',
  'mazda',
  'mazda',
  'mazda',
  'mazda',
  'mazda',
  'mazda',
  'mazda',
  'mazda',
  'mazda',
  'mazda',
  'mazda',
  'mazda',
  'mazda',
  'mazda',
  'mazda',
  'mercedes-benz',
  'mercedes-benz',
  'mercedes-benz',
  'mercedes-benz',
  'mercedes-benz',
  'mercedes-benz',
  'mercedes-benz',
  'mercedes-benz',
  'mercury',
  'mitsubishi',
  'mitsubishi',
  'mitsubishi',
  'mitsubishi',
  'mitsubishi',
  'mitsubishi',
  'mitsubishi',
  'mitsubishi',
  'mitsubishi',
  'mitsubishi',
  'mitsubishi',
  'mitsubishi',
  'mitsubishi',
  'nissan',
  'nissan',
  'nissan',
  'nissan',
  'nissan',
  'nissan',
  'nissan',
  'nissan',
  'nissan',
  'nissan',
  'nissan',
  'nissan',
  'nissan',
  'nissan',
  'nissan',
  'nissan',
  'nissan',
  'nissan',
  'peugot',
  'peugot',
  'peugot',
  'peugot',
  'peugot',
  'peugot',
  'peugot',
  'peugot',
  'peugot',
  'peugot',
  'peugot',
  'plymouth',
  'plymouth',
  'plymouth',
  'plymouth',
  'plymouth',
  'plymouth',
  'plymouth',
  'porsche',
  'porsche',
  'porsche',
  'porsche',
  'porsche',
  'renault',
  'renault',
  'saab',
  'saab',
  'saab',
  'saab',
  'saab',
  'saab',
  'subaru',
  'subaru',
  'subaru',
  'subaru',
  'subaru',
  'subaru',
  'subaru',
  'subaru',
  'subaru',
  'subaru',
  'subaru',
  'subaru',
  'toyota',
  'toyota',
  'toyota',
  'toyota',
  'toyota',
  'toyota',
  'toyota',
  'toyota',
  'toyota',
  'toyota',
  'toyota',
  'toyota',
  'toyota',
  'toyota',
  'toyota',
  'toyota',
  'toyota',
  'toyota',
  'toyota',
  'toyota',
  'toyota',
  'toyota',
  'toyota',
  'toyota',
  'toyota',
  'toyota',
  'toyota',
  'toyota',
  'toyota',
  'toyota',
  'toyota',
  'toyota',
  'volkswagen',
  'volkswagen',
  'volkswagen',
  'volkswagen',
  'volkswagen',
  'volkswagen',
  'volkswagen',
  'volkswagen',
  'volkswagen',
  'volkswagen',
  'volkswagen',
  'volkswagen',
  'volvo',
  'volvo',
  'volvo',
  'volvo',
  'volvo',
  'volvo',
  'volvo',
  'volvo',
  'volvo',
  'volvo',
  'volvo'],
 [0,
  0,
  0,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0])

In [37]:
list(cconteo)

[0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0]

---

In [41]:
for value in lista_carros:
    comparacion_conteo(value)

0
0
0
1
1
1
1
1
1
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0

In [42]:
for value in lista_carros:
    if value=="audi":
        print(1)
    else:
        print(0)

0
0
0
1
1
1
1
1
1
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0

---

In [50]:
list_empty = []
for valor in list(dataset["price"]):
    if valor != "?":
        list_empty.append(valor)

In [51]:
list_empty

['13495',
 '16500',
 '16500',
 '13950',
 '17450',
 '15250',
 '17710',
 '18920',
 '23875',
 '16430',
 '16925',
 '20970',
 '21105',
 '24565',
 '30760',
 '41315',
 '36880',
 '5151',
 '6295',
 '6575',
 '5572',
 '6377',
 '7957',
 '6229',
 '6692',
 '7609',
 '8558',
 '8921',
 '12964',
 '6479',
 '6855',
 '5399',
 '6529',
 '7129',
 '7295',
 '7295',
 '7895',
 '9095',
 '8845',
 '10295',
 '12945',
 '10345',
 '6785',
 '11048',
 '32250',
 '35550',
 '36000',
 '5195',
 '6095',
 '6795',
 '6695',
 '7395',
 '10945',
 '11845',
 '13645',
 '15645',
 '8845',
 '8495',
 '10595',
 '10245',
 '10795',
 '11245',
 '18280',
 '18344',
 '25552',
 '28248',
 '28176',
 '31600',
 '34184',
 '35056',
 '40960',
 '45400',
 '16503',
 '5389',
 '6189',
 '6669',
 '7689',
 '9959',
 '8499',
 '12629',
 '14869',
 '14489',
 '6989',
 '8189',
 '9279',
 '9279',
 '5499',
 '7099',
 '6649',
 '6849',
 '7349',
 '7299',
 '7799',
 '7499',
 '7999',
 '8249',
 '8949',
 '9549',
 '13499',
 '14399',
 '13499',
 '17199',
 '19699',
 '18399',
 '11900',
 '13200',
 '12440',
 '13860',
 '15580',
 '16900',
 '16695',
 '17075',
 '16630',
 '17950',
 '18150',
 '5572',
 '7957',
 '6229',
 '6692',
 '7609',
 '8921',
 '12764',
 '22018',
 '32528',
 '34028',
 '37028',
 '9295',
 '9895',
 '11850',
 '12170',
 '15040',
 '15510',
 '18150',
 '18620',
 '5118',
 '7053',
 '7603',
 '7126',
 '7775',
 '9960',
 '9233',
 '11259',
 '7463',
 '10198',
 '8013',
 '11694',
 '5348',
 '6338',
 '6488',
 '6918',
 '7898',
 '8778',
 '6938',
 '7198',
 '7898',
 '7788',
 '7738',
 '8358',
 '9258',
 '8058',
 '8238',
 '9298',
 '9538',
 '8449',
 '9639',
 '9989',
 '11199',
 '11549',
 '17669',
 '8948',
 '10698',
 '9988',
 '10898',
 '11248',
 '16558',
 '15998',
 '15690',
 '15750',
 '7775',
 '7975',
 '7995',
 '8195',
 '8495',
 '9495',
 '9995',
 '11595',
 '9980',
 '13295',
 '13845',
 '12290',
 '12940',
 '13415',
 '15985',
 '16515',
 '18420',
 '18950',
 '16845',
 '19045',
 '21485',
 '22470',
 '22625']

In [52]:
list_price = [int(value) for value in list_empty]

In [61]:
comparativo = list(map(lambda price_n:"muy caro" if price_n>10000 else "muy barato",list_price))

In [62]:
comparativo

['muy caro',
 'muy caro',
 'muy caro',
 'muy caro',
 'muy caro',
 'muy caro',
 'muy caro',
 'muy caro',
 'muy caro',
 'muy caro',
 'muy caro',
 'muy caro',
 'muy caro',
 'muy caro',
 'muy caro',
 'muy caro',
 'muy caro',
 'muy barato',
 'muy barato',
 'muy barato',
 'muy barato',
 'muy barato',
 'muy barato',
 'muy barato',
 'muy barato',
 'muy barato',
 'muy barato',
 'muy barato',
 'muy caro',
 'muy barato',
 'muy barato',
 'muy barato',
 'muy barato',
 'muy barato',
 'muy barato',
 'muy barato',
 'muy barato',
 'muy barato',
 'muy barato',
 'muy caro',
 'muy caro',
 'muy caro',
 'muy barato',
 'muy caro',
 'muy caro',
 'muy caro',
 'muy caro',
 'muy barato',
 'muy barato',
 'muy barato',
 'muy barato',
 'muy barato',
 'muy caro',
 'muy caro',
 'muy caro',
 'muy caro',
 'muy barato',
 'muy barato',
 'muy caro',
 'muy caro',
 'muy caro',
 'muy caro',
 'muy caro',
 'muy caro',
 'muy caro',
 'muy caro',
 'muy caro',
 'muy caro',
 'muy caro',
 'muy caro',
 'muy caro',
 'muy caro',
 'muy caro',
 'muy barato',
 'muy barato',
 'muy barato',
 'muy barato',
 'muy barato',
 'muy barato',
 'muy caro',
 'muy caro',
 'muy caro',
 'muy barato',
 'muy barato',
 'muy barato',
 'muy barato',
 'muy barato',
 'muy barato',
 'muy barato',
 'muy barato',
 'muy barato',
 'muy barato',
 'muy barato',
 'muy barato',
 'muy barato',
 'muy barato',
 'muy barato',
 'muy barato',
 'muy caro',
 'muy caro',
 'muy caro',
 'muy caro',
 'muy caro',
 'muy caro',
 'muy caro',
 'muy caro',
 'muy caro',
 'muy caro',
 'muy caro',
 'muy caro',
 'muy caro',
 'muy caro',
 'muy caro',
 'muy caro',
 'muy caro',
 'muy barato',
 'muy barato',
 'muy barato',
 'muy barato',
 'muy barato',
 'muy barato',
 'muy caro',
 'muy caro',
 'muy caro',
 'muy caro',
 'muy caro',
 'muy barato',
 'muy barato',
 'muy caro',
 'muy caro',
 'muy caro',
 'muy caro',
 'muy caro',
 'muy caro',
 'muy barato',
 'muy barato',
 'muy barato',
 'muy barato',
 'muy barato',
 'muy barato',
 'muy barato',
 'muy caro',
 'muy barato',
 'muy caro',
 'muy barato',
 'muy caro',
 'muy barato',
 'muy barato',
 'muy barato',
 'muy barato',
 'muy barato',
 'muy barato',
 'muy barato',
 'muy barato',
 'muy barato',
 'muy barato',
 'muy barato',
 'muy barato',
 'muy barato',
 'muy barato',
 'muy barato',
 'muy barato',
 'muy barato',
 'muy barato',
 'muy barato',
 'muy barato',
 'muy caro',
 'muy caro',
 'muy caro',
 'muy barato',
 'muy caro',
 'muy barato',
 'muy caro',
 'muy caro',
 'muy caro',
 'muy caro',
 'muy caro',
 'muy caro',
 'muy barato',
 'muy barato',
 'muy barato',
 'muy barato',
 'muy barato',
 'muy barato',
 'muy barato',
 'muy caro',
 'muy barato',
 'muy caro',
 'muy caro',
 'muy caro',
 'muy caro',
 'muy caro',
 'muy caro',
 'muy caro',
 'muy caro',
 'muy caro',
 'muy caro',
 'muy caro',
 'muy caro',
 'muy caro',
 'muy caro']

In [72]:
copia = list(dataset["price"])

In [74]:
len(copia[:201])

201

In [82]:
data = {"comparativo":comparativo,
       "precio":list_empty}

In [83]:
DF1 = pd.DataFrame(data=data)

In [84]:
DF1.head(15)

   comparativo precio
0     muy caro  13495
1     muy caro  16500
2     muy caro  16500
3     muy caro  13950
4     muy caro  17450
5     muy caro  15250
6     muy caro  17710
7     muy caro  18920
8     muy caro  23875
9     muy caro  16430
10    muy caro  16925
11    muy caro  20970
12    muy caro  21105
13    muy caro  24565
14    muy caro  30760

----

# Punto 8

In [85]:
class hash_table:
    def __init__(self):
        self.table = [None] * 127
    
    # Función hash
    def Hash_func(self, value):
        key = 0
        for i in range(0,len(value)):
            key += ord(value[i])
        return key % 127

    def Insert(self, value): # Metodo para ingresar elementos
        hash = self.Hash_func(value)
        if self.table[hash] is None:
            self.table[hash] = value
   
    def Search(self,value): # Metodo para buscar elementos
        hash = self.Hash_func(value);
        if self.table[hash] is None:
            return None
        else:
            return hex(id(self.table[hash]))
  
    def Remove(self,value): # Metodo para eleminar elementos
        hash = self.Hash_func(value);
        if self.table[hash] is None:
            print("No hay elementos con ese valor", value)
        else:
            print("Elemento con valor", value, "eliminado")
            self.table[hash] is None;

In [88]:
H = hash_table()
texto = "Alicia en el país de las maravillas"
H.Insert(texto)
print(H.Search(texto))

0x1d65b1c26b0

In [104]:
from hashtable import HashTable

In [105]:
H9 = HashTable(10)

In [106]:
books = [
    "ABC",
    "xxxxxxx",
    "uyyyyyyyy",
    "zzzzzzz"
]

In [107]:
lista_numero_n = [12,11,14,15]
sum(lista_numero_n)

52

In [ ]:
H9.

In [108]:
for book in books:
    key = sum(map(ord,book))
    H9.put(key,book)

AttributeError: 'HashTable' object has no attribute 'put'